# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "WIXDZGL-TV31451"
user = "SOUZACALEB"
password = "Snowflake.138"
role = "SYSADMIN"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
